### ISSUE TITLE
QR Code not recognized by iOS Camera

### ISSUE THREAD

**Issue by tberta** [smoqadam/url-to-qrcode-firefox-addon#14]
Hello,
I'm testing this addon and I'm having the following issue: Camera app on iOS 15.1 doesn't recognize the generated QR Code.
Camera app automatically recognize QR Code and display a notification allowing to open the link. 
https://support.apple.com/en-us/HT208843
But with this extension, it doesn't recognize the QR code.

**Comment by smoqadam** [comment]
I just tested the extension with the iOS 15.1 on iPhone 12 and it worked properly. Here is the screenshot:
![image](https://user-images.githubusercontent.com/1223848/140618159-36442041-6792-45d7-8f74-929fbfe0b7b2.png)

**Comment by tberta** [comment]
Hello, Thank you for your feedback. I tried again after your feedback and indeed it's working correctly! I don't know why I had the issue previously... probably a temporary issue on my phone resolved after a reboot? (I had other issues with iOS 15.1). Anyway, this extension is working greatly, thanks!
