### ISSUE TITLE
version 1.1 is not on addons.mozilla.org

### ISSUE THREAD

**Issue by johnnagro** [smoqadam/url-to-qrcode-firefox-addon#17]
I'm only seeing version 1.0 which seems to be broken. You may have fixed my issue in 1.1 - could you please deploy your new version to the addons site? Thanks!

https://addons.mozilla.org/en-US/firefox/addon/url-to-qrcode/

![Screen Shot 2023-01-19 at 9 19 40 AM](https://user-images.githubusercontent.com/31442/213466055-fcd187a1-5bdc-4fda-9b4f-d84c824b24c8.png)

**Comment by smoqadam** [comment]
Yes, I have fixed the issue on 1.1 and updated the package on the Firefox addon page, but it's been under review for a couple of days. Hopefully, they will release it any time soon. 

In the meantime, if you open the setting by clicking on the gear icon, and save the settings as it is, it shows the QrCode again. This is just a workaround until the new version comes out.

**Comment by PeterDaveHello** [comment]
🎉 

![image](https://github.com/smoqadam/url-to-qrcode-firefox-addon/assets/3691490/ed934b1d-e714-488f-9fe7-c7cd39abb338)
