### ISSUE TITLE
Margin should always be white, not system background

### ISSUE THREAD

**Issue by mmuman** [smoqadam/url-to-qrcode-firefox-addon#3]
# When using a [dark desktop theme](https://pod.g3l.org/posts/56781) along with Firefox, the margin becomes dark gray, which is quite bad for QR readability. At least here it prevents reading them from my tablet.

![shot_url_to_qr_bug](https://cloud.githubusercontent.com/assets/470143/16895831/2e798186-4b81-11e6-832d-a2c4ec8a8db8.png)

**Comment by OliverFriedrich** [comment]
This problem also occurs in version 0.6

It should be solved by adding a white border around the generated QR code.

**Comment by mmuman** [comment]
Or just forcing the background in the CSS maybe.

**Comment by smoqadam** [comment]
![url2qrcode](https://user-images.githubusercontent.com/1223848/30529868-32bcfe9e-9c57-11e7-8942-fde6b7331c9c.png)

It doesn't any problem in Firefox 57 nightly. But I'll check it in previous versions.

thanks

**Comment by losnappas** [comment]
Add a background-color: white; to body, please.
