### ISSUE TITLE
Some QR codes seem to be scaled with antialiasing

### ISSUE THREAD

**Issue by mmuman** [smoqadam/url-to-qrcode-firefox-addon#4]
which probably doesn't help the readability.
(here it's the QR code for [this article](http://bibliobs.nouvelobs.com/idees/20160331.OBS7480/la-strategie-de-la-mouche-comment-quelques-terroristes-font-trembler-les-grandes-nations.html).)
![shot_url_to_qr_bug](https://cloud.githubusercontent.com/assets/470143/16895849/b4868684-4b81-11e6-8a3f-8b9b650241f4.png)

**Comment by Ferada** [comment]
Seconded, maybe an added `image-rendering` or so would fix it?

**Comment by smoqadam** [comment]
Thanks guys for the report, 

Recently I was busy and I did not have enough time to work on it, as soon as I find free time I'll fix all the issues.

**Comment by mmuman** [comment]
:+1:
