### ISSUE TITLE
Adjust size of QR code

### ISSUE THREAD

**Issue by rugk** [smoqadam/url-to-qrcode-firefox-addon#7]
It would be nice if I could resize the QR code. Maybe you need a larger one or smaller one at times…

**Comment by f6fvy** [comment]
Definitely. Especially when used with a mobile phone !

**Comment by rugk** [comment]
Much has happened since I suggested this…
In the end I've decided to write my own QR code add-on. You can find it here: https://github.com/rugk/offline-qr-code/

It has many more features than just adjusting the size of the QR code though… :blush:

**Comment by f6fvy** [comment]
Great job. Thanks for sharing.

**Comment by smoqadam** [comment]
Added in version 1.0
